### ISSUE TITLE
Your api keys are exposed.

### ISSUE THREAD

**Issue by adriangalilea** [JayZeeDesign/microsoft-autogen-experiments#1]
https://github.com/JayZeeDesign/microsoft-autogen-experiments/blob/3f5578fe0d93996b6c18a5bd4e23778193ae39bf/content_agent.py#L32

I'd nuke it asap

Also browserless

https://github.com/JayZeeDesign/microsoft-autogen-experiments/blob/3f5578fe0d93996b6c18a5bd4e23778193ae39bf/content_agent.py#L62

**Comment by JayZeeDesign** [comment]
Thanks a lot Adrian! I've revoke them, appreciate it 🙏
